services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  grafana:
    image: grafana/grafana:latest
    user: "0"  # Forces root permissions to install plugins
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    restart: always
