[client]
showErrorDetails = false
toolbarMode = "minimal"

# [deployment]
# showDeploymentButton = false

[server]
address = "127.0.0.1"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#003366"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#001F54"

